### ISSUE TITLE
[Quest]Wanted:  "Hogger"

### ISSUE THREAD

**Issue by Narutohell** [NV-WoW/Bugtracker#108]
[Wanted:  "Hogger"] is not working (Hogger can't be targeted.
https://www.wowhead.com/quest=176/wanted-hogger

**Comment by AlainBx20** [comment]
confirmed

**Comment by TigerFist1983** [comment]
confirmed

**Comment by AlainBx20** [comment]
hogger can be targeted.
issue closed
