### ISSUE TITLE
Pets despawn on level up (dangerous if mid combat)

### ISSUE THREAD

**Issue by JamesGent** [NV-WoW/Bugtracker#11]
**Describe the bug:**
Pets despawn on level up (dangerous if mid combat)

**To Reproduce:**
1. Go to: '....'

Make a pet class

2. Action: (Quest.-/Object.-/Creature.-/Spell.-/Other related) '....'

Level up

3. Current behaviour: '....'

Pet ceases to exist

4. Expected behaviour:  '....'

Pet stays and levels up with you

5. Wowhead link: 'https://wowhead.com/....'
6. Server revision: 'Closed Alpha/Closed Beta/Beta vX....'

Game event areas, quests, vendors, etc should be present during the seasonal event period, and must be mentioned as [EVENT_NAME] tag.

**Current behavior:**
An exact description of what happened to you.

**Expected behavior:**

**(Not necessary but recommended) Screenshots:**

**(Not necessary but recommended) Videos:** 
If applicable, add a streamable (as an example) video link to help explain your problem.
(Recommended to use streamable website for example)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64 bit]
 - Client [e.g. Minimal Client or Full Client]

**Additional context**:

**Comment by wr4i7h-gg** [comment]
After level 10, the pet will stay with the player, the random respawn issue will disappear.
Below level 10, the pet is not a fully functional one.

**Comment by wr4i7h-gg** [comment]
Closed, and placed into the pinned post.
https://github.com/NV-WoW/Bugtracker/issues/14
