### ISSUE TITLE
[NPC] Lindsay (ID22)

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#110]
You are able to learn flight path from Lindsay also has herself as being a flight path for some reason.

![image](https://user-images.githubusercontent.com/29861833/128054874-4d5c1853-b917-4a07-b8bb-fe93e8160f25.png)

**Comment by xadowtek** [comment]
SQL:
-- Fix [NPC 65651] Lindsay
DELETE FROM creature WHERE guid = 261577;

**Comment by Grindknock** [comment]
Fixed
