### ISSUE TITLE
[NPC] Marshal Gryan Stoutmantle

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#121]
Duplicated NPC during the quest the quest ''Rise of the Brotherhood''

![image](https://user-images.githubusercontent.com/29861833/128064190-aaa11e5f-4657-4790-a2ac-cb0f8ba3c6f8.png)

**Comment by AlainBx20** [comment]
quest working as intended.
this issue will be closed for now.
