### ISSUE TITLE
[Quest] Fear no Evil (ID22)

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#123]
You are still able to spam click the Injured Stormwind Infantry and have the quest basicly instantly completed also the NPCS have beat lore hunter tooltips aka '' 0 dmg 110 hp'' etc

https://streamable.com/afh69x

**Comment by AlainBx20** [comment]
Confirmed.

**Comment by Grindknock** [comment]
Fixed
