### ISSUE TITLE
Looting item 131865 Darius' Handguards provides Represent tabard achievement

### ISSUE THREAD

**Issue by JamesGent** [NV-WoW/Bugtracker#13]
**Describe the bug:**
Looting item 131865 Darius' Handguards provides Represent tabard achievement

**To Reproduce:**
1. Go to: '....'

.additem 131865

2. Action: (Quest.-/Object.-/Creature.-/Spell.-/Other related) '....'

Observe results

3. Current behaviour: '....'

Represent achievement

4. Expected behaviour:  '....'

No tabard achievement for looting lvl 4 white wrist item

5. Wowhead link: 'https://wowhead.com/....'
6. Server revision: 'Closed Alpha/Closed Beta/Beta vX....'

Game event areas, quests, vendors, etc should be present during the seasonal event period, and must be mentioned as [EVENT_NAME] tag.

**Current behavior:**
An exact description of what happened to you.

**Expected behavior:**

**(Not necessary but recommended) Screenshots:**

**(Not necessary but recommended) Videos:** 
If applicable, add a streamable (as an example) video link to help explain your problem.
(Recommended to use streamable website for example)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64 bit]
 - Client [e.g. Minimal Client or Full Client]

**Additional context**:

**Comment by wr4i7h-gg** [comment]
There are plenty of incorrect achievements right now.
![image](https://user-images.githubusercontent.com/75091460/127840781-04aaa757-06ed-4b07-ba64-af4bc6abd8cd.png)
Represent, Fashionist for example. Those are proccing incorrectly.

**Comment by wr4i7h-gg** [comment]
Closed, and placed into the pinned post.
https://github.com/NV-WoW/Bugtracker/issues/14
