### ISSUE TITLE
[Quest] [night elf] [starting zone]

### ISSUE THREAD

**Issue by AlainBx20** [NV-WoW/Bugtracker#141]
### What client do you play on?

Minimal

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

after finishing felmoss corruption IIthalaine should give a followup quest :https://www.wowhead.com/quest=28734/a-favor-for-melithar
fellmoss corruption id :https://www.wowhead.com/quest=28714/fel-moss-corruption

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=frS1tfXka58

### Steps to reproduce the problem

.

**Comment by Trazzyx** [comment]
Please close, this is duplicate of [this](https://github.com/NV-WoW/Bugtracker/issues/55) . Always try to search first.

**Comment by AlainBx20** [comment]
issue closed.
duplicate.
