### ISSUE TITLE
Tabard/Shirt Achievment

### ISSUE THREAD

**Issue by Dman2008** [NV-WoW/Bugtracker#142]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Turning in the quest 'Protecting the Hard' or maybe hitting level 12 awarded me the following achievements: 'Fashionista: Tabard', 'Fashionista: Shirt', 'Ten Tabards

### Expected Blizzlike Behaviour

Should not get achievments

### Steps to reproduce the problem

turn in quest - unsure if repeatable

**Comment by AlainBx20** [comment]
we are aware of the bug :D
thanks for the report.
issue closed.
