### ISSUE TITLE
[Quest] AHHHHHHH! AHHH!! in redridge not completable

### ISSUE THREAD

**Issue by Wumblesnarf** [NV-WoW/Bugtracker#144]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

the quest directs you to enter the siege tank and kill 200 orcs, but you cannot interact with the tank in any way, leaving the quest uncompletable

### Expected Blizzlike Behaviour

the quest should be possible to complete

### Steps to reproduce the problem

start the quest 'AHHHHHHHHHHHH! AHHHHHHHHH!!!', and thats about as much as you can do

**Comment by l0ssm1** [comment]
This has been reported already

**Comment by Wumblesnarf** [comment]
oh my bad, should have double checked first
