### ISSUE TITLE
[Quest] Rallying the Defenders (ID66)

### ISSUE THREAD

**Issue by Dman2008** [NV-WoW/Bugtracker#147]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

I am able to plant the banner repeatedly at a single 'Loose Snow' pile.  Also, my character seems to teleport into and get stuck in every banner I place.

### Expected Blizzlike Behaviour

Unsure - never done quest before but behavior seems unexpected

### Steps to reproduce the problem

Plant banners during the quest

**Comment by AlainBx20** [comment]
Confirmed.
proof:https://www.youtube.com/watch?v=-z4aaTGFFfs

**Comment by Grindknock** [comment]
duplicated [#18](https://github.com/NV-WoW/Bugtracker/issues/18)
