### ISSUE TITLE
[Quest] [Rams on the Lam] bugged not working ( can be finished but needs rework )

### ISSUE THREAD

**Issue by sar4nix** [NV-WoW/Bugtracker#16]
wowhead link:https://www.wowhead.com/quest=25905/rams-on-the-lam
after some tries i managed to finish the quest but it's kinda broken and needs some rework    not every /whistle works

**Comment by wr4i7h-gg** [comment]
Cannot reproduce.
Tested on development realm and closed test.
https://youtu.be/HeOHzO99wOM
