### ISSUE TITLE
[NPC] Lady Vespira (ID22)

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#166]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Current Behaviour

Does not scale properly in darkshore

![image](https://user-images.githubusercontent.com/29861833/128390228-9a63da4b-29ce-45aa-a87b-27980070968b.png)

### Expected Blizzlike Behaviour

Should be scaling with zone

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
