### ISSUE TITLE
[NPC] Twilight Flameguard / Twilight Firesworn (ID22)

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#172]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Seems to be loads of these mobs all grouped up at one place in Ashenvale 

![Wow_C7uWNPjjX2](https://user-images.githubusercontent.com/29861833/128513500-2aab408a-65d1-46e0-bcfc-3c06b319c118.png)

### Expected Blizzlike Behaviour

Pretty sure they should be spread out and not grouped up like 20 mobs at once also pretty sure theres a phasing issue with a quest or something cause comparing to retail the mobs are not there meaning its some sort of quest or something thats suppose to have a diffrent phase ? 

![image](https://user-images.githubusercontent.com/29861833/128514642-bed176dc-088f-4bde-bf6a-534ec79b9f2c.png)

### Steps to reproduce the problem

.

**Comment by AlainBx20** [comment]
Confirmed.

**Comment by Grindknock** [comment]
fixed
