### ISSUE TITLE
[Quest][Dun Morogh] Ride to Ironforge (ID62)

### ISSUE THREAD

**Issue by TigerFist1983** [NV-WoW/Bugtracker#174]
"?" is not shown above npc and he won't grab quest.
[https://www.wowhead.com/quest=6391/ride-to-ironforge](url)
![WoWScrnShot_080621_192408](https://user-images.githubusercontent.com/86138081/128531194-df79089a-3c6f-40d3-a4fe-cb1ce3593e8a.jpg)

**Comment by Grindknock** [comment]
fixed
