### ISSUE TITLE
[Item] Stonesplitter Staff (ID66)

### ISSUE THREAD

**Issue by Dman2008** [NV-WoW/Bugtracker#179]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Staff has +20 INT on it as a level 19.  This seems high compared to other items having 3-5ish of stats.

### Expected Blizzlike Behaviour

Cant find legion database for comparison.

### Steps to reproduce the problem

Complete quest 'In Defense of the King's Lands'

**Comment by Grindknock** [comment]
![image](https://user-images.githubusercontent.com/75091460/128725738-f337d120-179f-41e6-a84e-bad47029fd07.png)
https://www.wowhead.com/item=58984/stonesplinter-staff?bonus=3631
