### ISSUE TITLE
[NPC] Keeper Heartwise / Tendril from Below (ID22) (Ashenvale)

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#180]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Keeper Heartwise isnt killing any Tendrils from below instead he just stands there causing there to be way to many Tendrils

![image](https://user-images.githubusercontent.com/29861833/128606170-00ac7465-1319-4e37-bb54-a85da1aa5d05.png)

The Tendrils isnt casting Shadow bolt they are just stationary Doing nothing at all

### Expected Blizzlike Behaviour

Keeper heartwise is suppose to cast Starfire onto the tendrils to kill them off and also say something as he is casting Starfire

The tendrils themselfs is suppose not be stationary doing nothing they should be casting shadowbolt when incombat with a player

https://www.wowhead.com/npc=33419/tendril-from-below#abilities

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
