### ISSUE TITLE
{NPC] Goblin Operator (ID22) (Ashenvale)

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#182]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

They are completly untargetable but they will aggro you

![Wow_zUgURZJtw5](https://user-images.githubusercontent.com/29861833/128609124-a43afb48-d572-47ee-9518-dfafb56ade99.png)

### Expected Blizzlike Behaviour

You should be able to actually target and aggro them pretty sure cause makes no sense for random npcs to aggro onto you and you being unable to target and actually kill them

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
fixed
