### ISSUE TITLE
[Quest] A Favor for Melithar (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#188]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

After completing quest https://www.wowhead.com/quest=28714/fel-moss-corruption there should be follow up quest https://www.wowhead.com/quest=28734/a-favor-for-melithar but no quest is offered.

### Expected Blizzlike Behaviour

favor for melithar quest should be open for me to take.

### Source

https://www.wowhead.com/quest=28734/a-favor-for-melithar

### Steps to reproduce the problem

1. complete fel moss corruption quest
2. you should see the following quest but you don't.

### Extra Notes

this is repost of [55](https://github.com/NV-WoW/Bugtracker/issues/55) to match the new bug report form.

**Comment by Grindknock** [comment]
fixed
