### ISSUE TITLE
[Quest] The land is in their blood (ID41) 

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#191]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Elder Brownpaw is not there so this quest can't be completed.
![image](https://user-images.githubusercontent.com/88363212/128623120-c59df0ee-60a1-4388-8412-f7104ca76786.png)

### Expected Blizzlike Behaviour

Elder Brownpaw should be there.

### Source

https://www.wowhead.com/quest=13575/the-land-is-in-their-blood

### Steps to reproduce the problem

1. take quest
2. go to target location.

### Extra Notes

This is repost of [80](https://github.com/NV-WoW/Bugtracker/issues/80) to match the new bugreport form.

**Comment by Grindknock** [comment]
Fixed
