### ISSUE TITLE
[Quest] The last wildkin (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#193]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Aroom is not there, so the quest can't be completed.

### Expected Blizzlike Behaviour

Aroom should be there after taking the quest.

### Source

https://www.wowhead.com/quest=13577/the-last-wildkin

### Steps to reproduce the problem

1. take quest
2. go to target location

### Extra Notes

Maybe you'll be unable to reproduce, see the old post about this. Aroom was there for AlainBx20(user) but not for me, so this might aswell just be a phasing issue rather than quest issue? I was playing nightelf.

This is probably the same issue as [190](https://github.com/NV-WoW/Bugtracker/issues/190), [191](https://github.com/NV-WoW/Bugtracker/issues/191) and [192](https://github.com/NV-WoW/Bugtracker/issues/192)

This is repost of [83](https://github.com/NV-WoW/Bugtracker/issues/83) to match the new bugtracker form.

**Comment by Grindknock** [comment]
Fixed
