### ISSUE TITLE
[NPC] Twilight Riflemen in Dun Modr (ID24)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#194]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

There are a lot of live Twilight Riflemen.
![WoWScrnShot_080821_140412](https://user-images.githubusercontent.com/74407627/128631427-306162b4-e13f-4b59-8221-a27755a28496.jpg)

### Expected Blizzlike Behaviour

They should all be dead.

https://www.youtube.com/watch?v=FotDV8t2bqM

### Source

https://www.youtube.com/watch?v=FotDV8t2bqM

### Steps to reproduce the problem

1. Go to Dun Modr in Wetlands

**Comment by Grindknock** [comment]
Fixed (core side issue, they name is still red, and full hp, but working on that visual issue)
