### ISSUE TITLE
[Item] Arena Treasure Chest (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#197]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

I'm pretty sure the gurubashi arena chest event is not working. Didn't see a single chest in 3 days, checking almost every 2 hours. I don't think i'm just unlucky since as far as i know nobody else is sniping/farming it as we are testing things.

![WoWScrnShot_080821_155405](https://user-images.githubusercontent.com/88363212/128634594-368a9055-76a7-426d-b4aa-2cbb057092a5.jpg)

### Expected Blizzlike Behaviour

[Short John Mithril](https://www.wowhead.com/npc=14508/short-john-mithril) should start event and spawn [arena treasure chest](https://www.wowhead.com/object=179697/arena-treasure-chest#comments) every 3 hour with /yell announcement.

### Source

[arena treasure chest comments](https://www.wowhead.com/object=179697/arena-treasure-chest#comments), also chest is working on live aswell so the event wasn't removed from game.

### Steps to reproduce the problem

1. go to gurubashi arena in strangelthorn vale
2. wait atleast 3 hours to check if the chest is spawning.

or simply:
1. check backend ingame implementation of event to see if the event is working

**Comment by Grindknock** [comment]
Chest fixed, and respawning in every 3 hours (from loot)
