### ISSUE TITLE
[NPC] Spirit Healer [UNIQUEID 42]

### ISSUE THREAD

**Issue by l0ssm1** [NV-WoW/Bugtracker#198]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

When you release spirit in Wetlands near the Slabchisel's Survey/Near big lake in the middle of map you get sent to graveyard that has 2 Spirit Healers.
![WoWScrnShot_080821_162152](https://user-images.githubusercontent.com/88226423/128635435-0d48c91b-7de6-4d7b-8061-70e9cd2c251d.jpg)

### Expected Blizzlike Behaviour

There should be only 1 Spirit Healer at the graveyard.

### Source

On Wowhead it shows only 1 coordinates for 1 Spirit Healer

![image](https://user-images.githubusercontent.com/88226423/128635504-b22bb94a-cea9-4ce0-8a10-8b7f98586ce3.png)

### Steps to reproduce the problem

Release Spirit near Slabchisel's Survey or near the Lake in the middle of Wetlands.

**Comment by Grindknock** [comment]
Fixed
