### ISSUE TITLE
[Item] Capital Bags (16 Slot)

### ISSUE THREAD

**Issue by xadowtek** [NV-WoW/Bugtracker#2]
**Describe the bug:**
Capital bags like Stormwind Bag, Ironforge Bag, Darnassus Bag, Gilneas Bag and so on, only have money requeriment.
no reputation requeriment, you can buy it and equip it.

![WoWScrnShot_072721_184629](https://user-images.githubusercontent.com/72521329/127197283-a3f593a7-add2-4913-9cc6-3bf9b3daa1ae.jpg)
![WoWScrnShot_072721_184645](https://user-images.githubusercontent.com/72521329/127197309-23177744-9ce4-4539-956c-b0a8f1f8b22a.jpg)

**Comment by wr4i7h-gg** [comment]
Fixed

**Comment by wr4i7h-gg** [comment]
Update: Need to clear your cache folder from your client in order to get it to work properly on your side.
Update 2: Panda related faction bags (Tushui & Huojin) only visible when the player reaches the suggested (faction-related) reputation level (Revered)
