### ISSUE TITLE
[Quest] [The rise of the darkspear]

### ISSUE THREAD

**Issue by AlainBx20** [NV-WoW/Bugtracker#203]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

script for the quest is not working properly ( Zuni RP)

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=EQAfYDlvZQ0

### Source

wowheadlink:https://www.wowhead.com/quest=24750/the-rise-of-the-darkspear

### Steps to reproduce the problem

Zuni should appear and start talking

### Extra Notes

.

**Comment by Grindknock** [comment]
Fixed
