### ISSUE TITLE
[NPC] Springpaw Cub (ID24)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#204]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Sometimes this NPC is attacking you even if it is dead. The same problem as #29

### Expected Blizzlike Behaviour

Ater you kill it, it should stay dead :)

### Source

https://www.wowhead.com/npc=15366/springpaw-cub

### Steps to reproduce the problem

1. Kill Springpaw Cub

**Comment by Grindknock** [comment]
Fixed
