### ISSUE TITLE
[Quest][Sunstrider Isle] Thirst Unending (ID24)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#206]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

When you use arcane torrent on Mana Wyrn, nothink happened.

### Expected Blizzlike Behaviour

After you use arcane torrent on mana wyrn the quest should be completed.

### Source

https://www.wowhead.com/quest=37439/thirst-unending
https://www.youtube.com/watch?v=t8cd1XEKLOg

### Steps to reproduce the problem

1. Go near Mana Wyrn
2. Use Arcane Torrent

**Comment by jacobx97** [comment]
Some classes can complete this quest. I completed it with my hunter, but with my paladin I cant

**Comment by Grindknock** [comment]
Fixed
