### ISSUE TITLE
{Quest] Proving Pit (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#207]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Current Behaviour

The Darkspear jailor just walks down and spawns a Captive Spitescale scout rather then unlocking the cage and the Captive Spitescale scout comming out from it

### Expected Blizzlike Behaviour

The Darkspear Jailor should walk towards the cage and unlock it having the Captive Spitescale Scout walk down into the pit rather then being spawned

https://www.youtube.com/watch?v=DhGxtvvIogk

### Steps to reproduce the problem

Take Quest
Talk to the Darkspear Jailor

**Comment by Grindknock** [comment]
Fixed
