### ISSUE TITLE
[NPC] Wretched Captive (ID24)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#208]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

NPC is moving around.

### Expected Blizzlike Behaviour

NPC should stay in front of Sergeant Kanren.

### Source

https://www.wowhead.com/npc=16916/wretched-captive#screenshots

### Steps to reproduce the problem

1. Go to Falconwing Square in Eversong Woods

**Comment by Grindknock** [comment]
Fixed
