### ISSUE TITLE
[NPC] Wretched Urchin (ID24)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#209]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Sometimes this NPC is attacking you even if it is dead. The same problem as #29

### Expected Blizzlike Behaviour

Ater you kill it, it should stay dead :)

### Source

https://www.wowhead.com/npc=15644/wretched-urchin

### Steps to reproduce the problem

1. Kill Wretched Urchin

**Comment by PhoenixXYZ** [comment]
Can confirm this its rarely it happens but its not only this NPC that does it its loads of NPCs across the map

**Comment by Grindknock** [comment]
Fixed
