### ISSUE TITLE
[Quest] Saving the Young (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#210]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Using the Bloodtalon Whistle near the tiny raptors does not give you credit instead you are forced to click on them to get credit

### Expected Blizzlike Behaviour

Using the Whistle near the tiny raptors should give you credit you should not be clicking on them to get credit.

https://www.youtube.com/watch?v=PqNINbDJk5o

### Steps to reproduce the problem

Take quest go near the tiny raptors and try using the whistle you wont get credit

**Comment by Grindknock** [comment]
Fixed
