### ISSUE TITLE
[NPC] Burning Blade Cultist Pet (ID22]

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#216]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

The burning blade Cultist imp is level 40 instead of being scaled with the burning blade cultist

![image](https://user-images.githubusercontent.com/29861833/128782517-4954cf7d-b524-4114-9390-a9d17a805f12.png)

### Expected Blizzlike Behaviour

Should be scaled to the burning blade cultist and not scaled alone 

### Source

https://www.wowhead.com/npc=3199/burning-blade-cultist

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
