### ISSUE TITLE
[NPC] Deer (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#218]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

So currently killing a dear in the nightelf starting zone gives you xp when it really shouldnt ?

https://streamable.com/qohr1n

### Expected Blizzlike Behaviour

They shouldnt be grating you experiance at all.

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
