### ISSUE TITLE
(NPC) Critters Durotar (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#219]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Same bug that was alliance is on horde aswell getting outland rep for killing snakes and some other critters in durotar

![image](https://user-images.githubusercontent.com/29861833/128785058-9482c14c-4a56-456e-a7ea-2f07dbf6c259.png)

### Expected Blizzlike Behaviour

Obv shouldnt be getting outland rep for killing critters in durotar just like elwynn forest

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
