### ISSUE TITLE
[Quest] Rescue the Survivors!

### ISSUE THREAD

**Issue by Nyxith** [NV-WoW/Bugtracker#22]
Draenei starting quest.
All Draenei Survivors are dead, so I can't use Gift of the Naruu on them.

Wowhead link: https://www.wowhead.com/quest=9283/rescue-the-survivors

![image](https://user-images.githubusercontent.com/31180004/127894305-268b2005-d683-49ba-8543-82edbd442ccf.png)

**Comment by wr4i7h-gg** [comment]
Fixed
