### ISSUE TITLE
[NPC] Cap'n Gravey (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#223]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Does not scale properly with level
![image](https://user-images.githubusercontent.com/29861833/128790795-327afb67-76bc-4bb9-9967-979e6f3ee0e8.png)

### Expected Blizzlike Behaviour

Should scale with level properly i mean level 12 trying to kill lvl 16 NPC

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
