### ISSUE TITLE
[NPC] Rat - undead starting zone reputation (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#226]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Rat in undead starting zone is giving rep with Ravenholdt and syndicate.
![WoWScrnShot_081021_062158](https://user-images.githubusercontent.com/88363212/128807852-f9a252a7-be35-4b03-a858-5fbea0d93e53.jpg)

### Expected Blizzlike Behaviour

Should not give reputation with those factions.

### Source

https://www.wowhead.com/npc=4075/rat

### Steps to reproduce the problem

1. make undead
2. kill rat, there are plenty around

**Comment by AlainBx20** [comment]
confirmed.
reputation given ravenholdt and the syndicate

**Comment by Grindknock** [comment]
Fixed
