### ISSUE TITLE
[Item] Pockmarked Cloth Belt (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#239]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Multiple mobs in Tirisfal Glades are dropping this item while I think that it shouldn't drop.

### Expected Blizzlike Behaviour

The item should not drop in Tirisfal Glades at all.

### Source

https://www.wowhead.com/item=62100/pockmarked-cloth-belt?bonus=6656

### Steps to reproduce the problem

check loot tables of mobs spawning in tirisfal glades if possible.

### Extra Notes

I wanted to proof that with screenshot but I got no luck in getting next one and I didn't prtscr at the first time sadly..

**Comment by Grindknock** [comment]
Fixed
