### ISSUE TITLE
[Quest][Eversong Woods] The Dwarven Spy (ID24) (possibly not a bug)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#243]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

When you talk to Prospector Anvilward nothink happened.

### Expected Blizzlike Behaviour

You should talk to Prospector Anvilward and he should go to house with you, then you should kill him.
https://www.wowhead.com/quest=8483/the-dwarven-spy

### Source

https://www.wowhead.com/quest=8483/the-dwarven-spy

### Steps to reproduce the problem

1. Take the quest
2. Talk with the dwarf

**Comment by jacobx97** [comment]
Looks like it is some phasing problem, I just speak after some time with the dwarf again and it is working.

**Comment by AlainBx20** [comment]
Phasing problem, sometimes it works flawlessly other times the script breaks.

**Comment by Grindknock** [comment]
Fixed
