### ISSUE TITLE
[Zone] [Orgrimmar] Gifts (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#246]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Currently at 49,34, 77,92 there is the Winter Veil Gifts

![image](https://user-images.githubusercontent.com/29861833/128863609-acee0740-8428-498c-90dd-7c47f05f029e.png)

### Expected Blizzlike Behaviour

They should only appear during the event ''Feast of Winter Veil''

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
