### ISSUE TITLE
[NPC] Geolord Mottle (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#247]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Currently not scaling properly npc is still level 6 while im level 15

![image](https://user-images.githubusercontent.com/29861833/128864707-43148f48-7fce-4ec3-a5ed-2c25222a7e85.png)

### Expected Blizzlike Behaviour

Should properly scale with level and not be level 6 when im currently level 15.

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
