### ISSUE TITLE
[NPC] Kreenig Snarlsnout (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#248]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Not properly scaling at all
![Wow_w6z5iuxFSY](https://user-images.githubusercontent.com/29861833/128866644-7af0a2ac-fe48-445e-bcc3-c12e5de191e6.png)

### Expected Blizzlike Behaviour

Should scale properly like all the other mobs nearby and not be level 12 while im level 15

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
