### ISSUE TITLE
[NPC] Razormane Thornweaver (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#249]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

![Wow_4e3Yy4qu0E](https://user-images.githubusercontent.com/29861833/128867073-ca1313d8-e529-462d-a404-f7f349e7a85b.png)
Not scaling properly 

### Expected Blizzlike Behaviour

Should scale properly like the other razormane mobs inside the cave

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
