### ISSUE TITLE
[Item] Small Pile of NV Credits (ID22)

### ISSUE THREAD

**Issue by PhoenixXYZ** [NV-WoW/Bugtracker#251]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

So got lucky enough to get one and says its suppose to give 10 but instead i only got 1 added
![Wow_6jsjmQqyM4](https://user-images.githubusercontent.com/29861833/128875044-dfbf0f52-fdaf-4cbe-af93-2b46fa088792.png)

![image](https://user-images.githubusercontent.com/29861833/128875369-3bc21a07-f58c-4aff-9744-1b833c331c72.png)
previously had 35 now 36

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

**Comment by AlainBx20** [comment]
small piles of NV gives only 1 NVC
the current visual bug will be fixed soon :) .

**Comment by Grindknock** [comment]
Visual bug, already fixed. You need to DELETE your Cache folder inside your client, and this issue will gone.
