### ISSUE TITLE
[General] Rested experience gain (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#254]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

Generic

### Current Behaviour

From the screenshot (chat window) you can see that i was offline on this character for 19 hours. From the rest experience formula i'm supposed to get 5% of exp bar as rested experience for every 8hrs of offline (more if in inn, but i wasn't at inn). Nevertheless I got nothing so far.
![image](https://user-images.githubusercontent.com/88363212/129003118-d1a8f3c2-65bb-41b7-ac8a-3a407b2f2d35.png)

### Expected Blizzlike Behaviour

Rested Experience accrues at a rate of 5%, or 1 bubble, for every 8 hours of rest that your character takes. 

### Source

https://www.wowhead.com/guides/rested-experience-bonuses-leveling-warcraft
https://wowpedia.fandom.com/wiki/Rest

### Steps to reproduce the problem

1. create char
2. be offline for more than 8 hours
3. see that you don't get rested experience.

**Comment by Grindknock** [comment]
Visual bug.
The rest option is disabled for out-side of cities and inns
