### ISSUE TITLE
[QUEST NPC(Enemy)] Utroka the Keymistress/ Her pet level scaling is wrong.

### ISSUE THREAD

**Issue by l0ssm1** [NV-WoW/Bugtracker#26]
Enemy NPC for quest [Jorgensen] seems to have problem with level scaling. Level of the NPC is fine but she summons a Felhunter pet that is lvl 40.

Wowhead link: https://www.wowhead.com/npc=43350/utroka-the-keymistress

**Comment by wr4i7h-gg** [comment]
Fixed
