### ISSUE TITLE
[Quest][Ruins of Gilneas] What Tomorrow Brings (ID24)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#261]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

When you use telescope and the "cinematic" ends, nothink happend.

### Expected Blizzlike Behaviour

After you use the telescope the quest should be completed.

https://www.youtube.com/watch?v=c4c-fgpeJKI

### Source

https://www.wowhead.com/quest=27401/what-tomorrow-brings
https://www.youtube.com/watch?v=c4c-fgpeJKI

### Steps to reproduce the problem

1. Take the quest
2. Use telescope

**Comment by Grindknock** [comment]
You can complete the quest, but no cinematic triggers.
