### ISSUE TITLE
invader in our home quest

### ISSUE THREAD

**Issue by corto35150** [NV-WoW/Bugtracker#266]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Hello, so i just started playing in the orc starting and upon completing the "invaders in our home quest" i got the achievement 
"representent" which need you to collect a tabard slot appearance. Im not sure but i dont think it should give it.

### Expected Blizzlike Behaviour

it should not give an achievement 

### Source

https://www.wowhead.com/quest=25172/invaders-in-our-home

https://www.wowhead.com/achievement=621/represent

### Steps to reproduce the problem

1. do the "invader in our home quest" and pick the leather chest 

### Extra Notes

no extra note

**Comment by Grindknock** [comment]
Already known issue.
https://github.com/NV-WoW/Bugtracker/issues/14
