### ISSUE TITLE
Quest

### ISSUE THREAD

**Issue by Koyosu** [NV-WoW/Bugtracker#27]
Billy cannot be found to complete the quest pie for billy
![image](https://user-images.githubusercontent.com/82822996/127901341-298b958e-0a71-4964-92ac-e1dad54ab1e8.png)

https://www.wowhead.com/quest=86/pie-for-billy

**Comment by wr4i7h-gg** [comment]
Invalid. The quest is completable, just the indicator is wrong.
![image](https://user-images.githubusercontent.com/75091460/127987148-b7c2025b-ffac-4ef6-bdc1-9e07fc28964e.png)
