### ISSUE TITLE
Lazy peon quest doesnt work

### ISSUE THREAD

**Issue by corto35150** [NV-WoW/Bugtracker#270]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

The "Lazy peon" quest doesnt seem to work, whenever you hit sleeping peon with the mace it does the animation and the sound but the peon doesnt work 

https://www.wowhead.com/quest=37446/lazy-peons

### Expected Blizzlike Behaviour

The peon should awake 

### Source

https://www.wowhead.com/quest=37446/lazy-peons

### Steps to reproduce the problem

1. create an orc character 
2. do the Lazy peon quest

**Comment by Grindknock** [comment]
Duplicated.
Please use the search function
