### ISSUE TITLE
[Quest] [Achievement] Finishing "Recruitment" quest gives "Represent" achievement.

### ISSUE THREAD

**Issue by Fingon93** [NV-WoW/Bugtracker#271]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

When I finished the Recruitment quest, one of the first undead quests where you have to go around with a big guy picking up 6 corpses. After turning it in it gave me the "represent" achievement.

The "Represent" achievement is awarded when acquiring a Tabbard. 

I have no tabbard. The quest does not give a tabard.

### Expected Blizzlike Behaviour

You should not be awarded Represent.

### Source

It literally makes no sense.

### Steps to reproduce the problem

1. Do Recruitment quest.
2. Obtain the achievement.

**Comment by Grindknock** [comment]
Duplicated
https://github.com/NV-WoW/Bugtracker/issues/14
