### ISSUE TITLE
[Skill] [Achievement] Learning Cooking gives the award "Short Order Cook"

### ISSUE THREAD

**Issue by Fingon93** [NV-WoW/Bugtracker#279]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

When I learned cooking from "The Chef" in Brill I got the achievement Learn 25 Cooking recipes and 50 cooking recipes despite the fact that I only have 3 recipes.

### Expected Blizzlike Behaviour

Not earning those achievements.

### Source

Common knowledge.

### Steps to reproduce the problem

1. Learn cooking in Brill by "The Chef".

**Comment by Grindknock** [comment]
Duplicated
https://github.com/NV-WoW/Bugtracker/issues/14
