### ISSUE TITLE
Critters giving unintended rep when killed.

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#28]
The spider critters inside Jasperlode Mine seems to be giving outland reputation when they are being killed 
![image](https://user-images.githubusercontent.com/29861833/127905533-4e401b6e-ffef-4ca8-ba08-8bc6df0a9beb.png)

**Comment by PhoenixTV1337** [comment]
Seems to be the case not only for spiders inside the mine but also other critters in Elwynn Forest

**Comment by wr4i7h-gg** [comment]
Fixed
