### ISSUE TITLE
[Quest] [Achievement] After completing "Graverobbers" quest I got the "Ten Tabards" Achievement.

### ISSUE THREAD

**Issue by Fingon93** [NV-WoW/Bugtracker#281]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

Generic

### Current Behaviour

After completing the "Graverobbers" quest I got the "Ten Tabbards" Achievement.
I think it's related to the number of quests I have completed.

### Expected Blizzlike Behaviour

There should be no tabard achievement for completing quests.

### Source

Common sense.

### Steps to reproduce the problem

1. Complete the "Graverobbers" quest.
2. Or complete a number of quests.

**Comment by Grindknock** [comment]
Duplicated
https://github.com/NV-WoW/Bugtracker/issues/14
