### ISSUE TITLE
Clean Up Bags Not Working

### ISSUE THREAD

**Issue by flashmobsta** [NV-WoW/Bugtracker#282]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

"Clean Up Bags" button not working.

### Expected Blizzlike Behaviour

I believe it's supposed to organize your bags.

### Steps to reproduce the problem

Click "Clean Up Bags" button on Inventory.

### Extra Notes

I'm a Worgen if that makes any difference.

**Comment by Grindknock** [comment]
Duplicated
