### ISSUE TITLE
[Spell][Warlock] Pet despawn

### ISSUE THREAD

**Issue by Lunasoll** [NV-WoW/Bugtracker#293]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Pet despawns in 2 cases so far:

1. Character gains level
2. Logging out

### Expected Blizzlike Behaviour

Pet should remain summoned when level is gained and when logging back in. 

### Steps to reproduce the problem

1. Gain level with a pet class
2. Log off when pet is summoned and log back in.

**Comment by Grindknock** [comment]
Known issue
Check the pinned post, https://github.com/NV-WoW/Bugtracker/issues/14
