### ISSUE TITLE
Gnome starting area helicopters 

### ISSUE THREAD

**Issue by l0ssm1** [NV-WoW/Bugtracker#3]
**Describe the bug:**When you click on mini helicopters in gnome starting area you can sometimes go through the floor and if you leave you can fall through terrain and end up falling until you die.
 A clear and concise description of what the bug is, where you found it and how to reproduce that issue.
falling through terrain when you leave mini helicopter and are unable to revive.
**To Reproduce:**Enter mini helicopter at gnome starting area.
1. Go to: 'Gnome starting Area'
2. Action: (Quest.-/Object.-/Creature.-/Spell.-/Other related) 'Interact with Mini Helicopter'
3. Current behaviour: 'Going through terrain and walls'
4. Expected behaviour:  'Not sure but probably for quest (To take you to the next part of gnome starting area'
5. Wowhead link: 'https://www.wowhead.com/npc=126792/target-acquisition-device'
6. Server revision: 'Closed Beta'

Game event areas, quests, vendors, etc should be present during the seasonal event period, and must be mentioned as [EVENT_NAME] tag.

**Current behavior:**
An exact description of what happened to you.

**Expected behavior:**

**(Not necessary but recommended) Screenshots:**

**(Not necessary but recommended) Videos:** 
If applicable, add a streamable (as an example) video link to help explain your problem.
(Recommended to use streamable website for example)

**WoWHead Link:**
Add a wowhead link about your issue (please check the correct 4.3.4 15595 changelog for it).

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Client Full Client

**Additional context**:

**Comment by wr4i7h-gg** [comment]
Fixed
