### ISSUE TITLE
[Feature][Bag] Cleanup bags

### ISSUE THREAD

**Issue by rikardbq** [NV-WoW/Bugtracker#310]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Pressing cleanup bags doesnt do anything

### Expected Blizzlike Behaviour

Cleanup bags button cleans up my bags

### Steps to reproduce the problem

Open bags and press cleanup bags

**Comment by AlainBx20** [comment]
duplicate issue
issue is known
