### ISSUE TITLE
[Profession][Mining] Blood shards

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#32]
Mining copper ore as alliance in Elwynn Forest also gives Blood Shards which should only be possible for horde to get after you had completed a certain quest in The Barrens

![image](https://user-images.githubusercontent.com/29861833/127906790-6b73fa3b-7ce1-489e-a24b-9f900164ed1a.png)

**Comment by l0ssm1** [comment]
Can confirm.

**Comment by wr4i7h-gg** [comment]
Fixed
