### ISSUE TITLE
[Quest] Certain completed quests are not showing on world map as 'question marks'

### ISSUE THREAD

**Issue by Lunasoll** [NV-WoW/Bugtracker#332]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Certain completed quests are not showing on world map as 'question marks' at the location where they can be turned in. 

### Expected Blizzlike Behaviour

All completed quests should show question marks on World Map at the location where quest can be turned in. 

### Steps to reproduce the problem

These are a few quests that I found not showing completed question marks at world map in Dun Morough
1. A Hand at the Ranch
2. Bound for Kharanos
3. Help from Steelgrill's Report

<a href="https://ibb.co/TrKhtCC"><img src="https://i.ibb.co/Bw4sB11/Screenshot-1.jpg" alt="Screenshot-1" border="0"></a>

### Extra Notes

This is not only for Dun Morough. In every zone, there are some quests that won't show on world map as completed so it's hard to find which location to go to for turn in.

**Comment by AlainBx20** [comment]
Fixed.
