### ISSUE TITLE
[Quest] Rallying the Defenders, getting stuck

### ISSUE THREAD

**Issue by Lunasoll** [NV-WoW/Bugtracker#335]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

In this quest, you need to place a banner on the ground. When banner is placed, character gets stuck inside the banner and it's hard to get out. 

<a href="https://ibb.co/8b81ntS"><img src="https://i.ibb.co/7QysxL6/Screenshot-1.jpg" alt="Screenshot-1" border="0"></a>

### Expected Blizzlike Behaviour

Character should not get stuck

### Source

https://www.youtube.com/watch?v=j-Rzzlstp-k

### Steps to reproduce the problem

1. Accept quest
2. Use quest item (banner) on loose snow

### Extra Notes

Not gamebreaking, still possible to get out but after a few tries only.

**Comment by Grindknock** [comment]
duplicated [#18](https://github.com/NV-WoW/Bugtracker/issues/18)
