### ISSUE TITLE
[Quest]Wanted: "Hogger"

### ISSUE THREAD

**Issue by BradleyShea** [NV-WoW/Bugtracker#336]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Hogger cannot be targeted.

![image](https://user-images.githubusercontent.com/89138378/129892766-631326ec-a0f6-419c-b06d-d064ce050c4d.png)

### Expected Blizzlike Behaviour

Hogger should be targetable.

### Source

https://www.wowhead.com/quest=176/wanted-hogger

### Steps to reproduce the problem

1. Accept quest Wanted "Hogger"
2. Approach Quest Area

**Comment by xadowtek** [comment]
Duplicated #75

**Comment by AlainBx20** [comment]
fixed.
