### ISSUE TITLE
[NPC] Orgrimmar guards not putting up map markers

### ISSUE THREAD

**Issue by Lapaco94** [NV-WoW/Bugtracker#343]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Asking the guards to direct me to professions trainers does not put a marker on the map.

### Expected Blizzlike Behaviour

They should put a marker on the map.

### Steps to reproduce the problem

1. Talk to guards

**Comment by AlainBx20** [comment]
Fixed.
