### ISSUE TITLE
[Mulgore] [Camp Narache] Quests are displayed properly in questlog, but when clicked say the quest is in Eversong Woods.

### ISSUE THREAD

**Issue by Lapaco94** [NV-WoW/Bugtracker#350]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Clicking Rite Of Courage, Stop The Thorncallers, Feed of Evil, The Battleboars, Rite of Honor, Rites of the Earthmother in the questlog references to Eversong Woods.

Missing quest marker: Go to Adana

### Expected Blizzlike Behaviour

When clicked, it opens the Camp Narache map and show the proper location.

### Source

https://www.wowhead.com/quest=14456/rite-of-courage
https://www.wowhead.com/quest=14455/stop-the-thorncallers
https://www.wowhead.com/quest=14461/feed-of-evil
https://www.wowhead.com/quest=14459/the-battleboars
https://www.wowhead.com/quest=14460/rite-of-honor
https://www.wowhead.com/quest=23733/rites-of-the-earthmother

Missing quest marker: https://www.wowhead.com/quest=14458/go-to-adana

### Steps to reproduce the problem

1. Do the Mulgore starting zone
2. Click on any of the quests and watch it take you to Eversong Woods.

**Comment by AlainBx20** [comment]
Fixed
