### ISSUE TITLE
[Mulgore] [Bloodhoof Village] [Quests] Few quests missing markers

### ISSUE THREAD

**Issue by Lapaco94** [NV-WoW/Bugtracker#353]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

Both those quests don't have markers on the map.

### Expected Blizzlike Behaviour

They should have a marker on the map.

### Source

https://www.wowhead.com/quest=26179/the-venture-co

https://www.wowhead.com/quest=24441/thunderhorn-totem

### Steps to reproduce the problem

1. Accept quests, see no marker.

**Comment by Lapaco94** [comment]
https://www.wowhead.com/quest=749/the-ravaged-caravan
The ravaged Caravan is also missing a marker on delivery.

**Comment by AlainBx20** [comment]
Fixed.
