### ISSUE TITLE
[Mega thread] low level caster mobs

### ISSUE THREAD

**Issue by Grindknock** [NV-WoW/Bugtracker#362]
If you encounter a caster mob, what does irrational huge damage, please send it here, not open a new issue report.

Example:
NPC's name - Wowhead link

**Comment by EnnarAnarchist** [comment]
Windfury Wind Witch - https://www.wowhead.com/npc=2963/windfury-wind-witch

Lightning bolt hits for like 25% of HP on the same level.

**Comment by deadspear** [comment]
Grimscale Seer - https://www.wowhead.com/npc=15950/grimscale-seer

**Comment by Mezma99** [comment]
https://www.wowhead.com/npc=44729/twilight-encroacher' Spell they use is Twilight Fissure, hits for 543 damage.

**Comment by Grindknock** [comment]
Fixed
