### ISSUE TITLE
[Quest][Azshara] The Blackmaw Doublecross (ID24)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#363]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

None of the dialog options in menu is working when you talk with Ungarl.

### Expected Blizzlike Behaviour

You should be able to talk with Ungarl when you are friendly with The Blackmaw after use Ambassador Disguise and then you should be able to kill them.

https://www.youtube.com/watch?v=jZ0rePxtNQI

### Source

https://www.youtube.com/watch?v=jZ0rePxtNQI
https://www.wowhead.com/quest=14435/the-blackmaw-doublecross

### Steps to reproduce the problem

1. Get the quest
2. Use Ambassador Disguise
3. Go to the cave where Ungarl is
4. Talk with him

**Comment by Grindknock** [comment]
Fixed
