### ISSUE TITLE
Warrior talent - Shockwave

### ISSUE THREAD

**Issue by Koyosu** [NV-WoW/Bugtracker#364]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

The talent is working as it should but when you log out then log in its unusable and you have to change your talent then change it back to be usable again, untill you logout, then the cycle repeats.

### Expected Blizzlike Behaviour

Not doing anything written above

### Steps to reproduce the problem

.

**Comment by Grindknock** [comment]
Fixed
