### ISSUE TITLE
[Quest][Dun Morogh] Pack Your Bags

### ISSUE THREAD

**Issue by psajdak45** [NV-WoW/Bugtracker#365]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

When you pick up [Leftover Boar Meat](https://www.wowhead.com/item=49756/leftover-boar-meat) and [Ragged Wolf-Hide Cloak](https://www.wowhead.com/item=49755/ragged-wolf-hide-cloak) the loot window doesnt appear and cant finish the quest.

And the [Coldridge Beer Flagon](https://www.wowhead.com/item=49755/ragged-wolf-hide-cloak) also contains [Wildhammer Ale](https://www.wowhead.com/item=62327/wildhammer-ale)

### Expected Blizzlike Behaviour

Just pick up the items
https://www.youtube.com/watch?v=uynxYytzTiM

### Source

https://www.wowhead.com/quest=24492/pack-your-bags

** Note: the locations of the items appear to have changed in WoD pre-patch 6.0.2, and are no longer the same each time

### Steps to reproduce the problem

1. Take the quest
2. Pick up objects needed for the quest

**Comment by Grindknock** [comment]
Fixed
