### ISSUE TITLE
[Quest] [Sen'jin Village] Cleaning Up the Coastline

### ISSUE THREAD

**Issue by Snackhrot** [NV-WoW/Bugtracker#366]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

The completed quest mark on the world map and minimap is showing incorrectly on a different spot, in the sea.

### Expected Blizzlike Behaviour

It's supposed to be shown in the village where the NPC is.

### Steps to reproduce the problem

1. Take the quest "Cleaning Up the Coastline"
2. Complete it by collecting 5 Crawler Mucus
3. Open your map to see where it shows to return the quest

**Comment by Grindknock** [comment]
Fixed
