### ISSUE TITLE
Quest Marks randomly poping on map after finishing quests!

### ISSUE THREAD

**Issue by BlazertheAshbringer** [NV-WoW/Bugtracker#368]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

1-20

### Current Behaviour

You can see on SS of maps that is showing on map
https://i.imgur.com/3HpPPer.png

https://i.imgur.com/lpOdiIS.png

sorry for spamming links in post but dont know what to put in other boxes :D

### Expected Blizzlike Behaviour

.https://i.imgur.com/3HpPPer.png

https://i.imgur.com/lpOdiIS.png

### Source

.https://i.imgur.com/3HpPPer.png

https://i.imgur.com/lpOdiIS.png

### Steps to reproduce the problem

https://i.imgur.com/3HpPPer.png

https://i.imgur.com/lpOdiIS.png

### Extra Notes

https://i.imgur.com/3HpPPer.png

https://i.imgur.com/lpOdiIS.png

**Comment by Grindknock** [comment]
Fixed
