### ISSUE TITLE
disgusting oozling 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#372]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

upon using the item after looting it in a oozling bag 
https://www.wowhead.com/item=20769/disgusting-oozeling
you get the pet  lil' leftovers 
https://www.wowhead.com/npc=78895/lil-leftovers

### Expected Blizzlike Behaviour

the pet you are supposed to learn from it is 
https://www.wowhead.com/npc=15429/disgusting-oozeling

### Source

https://www.wowhead.com/npc=15429/disgusting-oozeling

### Steps to reproduce the problem

1. farm oozling bags 
2. get lucky enough to get the item in a bag 
3. use the item

**Comment by Grindknock** [comment]
Fixed
