### ISSUE TITLE
quest : battle for the skies ( panda starting area ) 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#373]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

during the quest battle for the skies : https://www.wowhead.com/quest=29786/battle-for-the-skies

the fight starts normally but once you kill Zhao-Ren : https://www.wowhead.com/npc=55786/zhao-ren

he instantly respawns but this time instead of flying around he attacks  like any normal monster  he one shots any level 10 and has about 400k hp 
 
also the npc for the quest is very close to where he first die making it very hard to deliver / get the next quest had to die about 6 times 

### Expected Blizzlike Behaviour

once you shoot him with the fireworks untill he reaches 0 hp hes supposed to die and stay dead for a while making it simple for the player to move on 

### Source

https://www.youtube.com/watch?v=qof7okkjxU0

### Steps to reproduce the problem

1. shoot zhao-ren with the fireworks while he flies around till he dies 
2. he should instantly respawn upon death 
3. run for your life

**Comment by Grindknock** [comment]
duplicated (https://github.com/NV-WoW/Bugtracker/issues/56)
