### ISSUE TITLE
[quest]  [Dun Morogh] Rallying the defenders 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#374]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

https://www.wowhead.com/quest=26085/rallying-the-defenders

you can currently plant the banner 8 times in the same patch of snow 

### Expected Blizzlike Behaviour

you are suposed to find 8 different patches of snow to plant each banners 

### Source

https://www.youtube.com/watch?v=-z4aaTGFFfs

### Steps to reproduce the problem

1. find a patch of snow and keep clicking the banner item 

### Extra Notes

not exactly a vital fix

**Comment by Grindknock** [comment]
[#18](https://github.com/NV-WoW/Bugtracker/issues/18)
