### ISSUE TITLE
Quest -  ID: 26562 - Redridge Mountains

### ISSUE THREAD

**Issue by BlazertheAshbringer** [NV-WoW/Bugtracker#379]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

Generic

### Current Behaviour

Danforth Missing in cave
Map shows where quest is:
https://i.imgur.com/wcXHX4Q.png
Cave where quest is: 
https://i.imgur.com/fl6Iroe.png
https://i.imgur.com/EekFP8x.png

### Expected Blizzlike Behaviour

Video how it should work: https://www.youtube.com/watch?v=k68rmbuytf4

### Source

https://www.youtube.com/watch?v=k68rmbuytf4

### Steps to reproduce the problem

https://www.youtube.com/watch?v=k68rmbuytf4

### Extra Notes

https://www.youtube.com/watch?v=k68rmbuytf4

**Comment by Grindknock** [comment]
Fixed
