### ISSUE TITLE
[Quests][Dun Morogh] Wrong question mark positions

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#38]
When you complete some quest the question mark is at wrong position on map.

Here is list of Dun Morogh quests where I found the problem:
https://www.wowhead.com/quest=25667/culling-the-wendigos
 https://www.wowhead.com/quest=25668/pilfered-supplies
 https://www.wowhead.com/quest=313/forced-to-watch-from-afar
 https://www.wowhead.com/quest=25905/rams-on-the-lam
 https://www.wowhead.com/quest=315/the-perfect-stout 
https://www.wowhead.com/quest=25724/frostmane-aggression 
https://www.wowhead.com/quest=26380/bound-for-kharanos 
https://www.wowhead.com/quest=6392/return-to-gremlock
 https://www.wowhead.com/quest=26078/extinguish-the-fires 
https://www.wowhead.com/quest=26112/demanding-answers

**Comment by wr4i7h-gg** [comment]
Every quest markers and pois has been fixed.
Some reference
![image](https://user-images.githubusercontent.com/75091460/128163530-d7f5ea6a-a34a-45af-add6-049da1e79569.png)
![image](https://user-images.githubusercontent.com/75091460/128163552-08d4166b-763a-40b7-8ded-41559fab35b7.png)
![image](https://user-images.githubusercontent.com/75091460/128163570-3d575758-31d7-4572-b66c-513057daeb85.png)
![image](https://user-images.githubusercontent.com/75091460/128163598-78339c72-54bb-4d7b-83e9-a35c883f101e.png)
![image](https://user-images.githubusercontent.com/75091460/128163623-54f9d1a5-7852-4ae3-8b38-5218bea3236f.png)
![image](https://user-images.githubusercontent.com/75091460/128163652-25925077-bb60-427a-8298-fd67ff633754.png)

When the quests are finished:
![image](https://user-images.githubusercontent.com/75091460/128163771-a895fcee-a4f4-4231-9e3c-f7626cb22142.png)
