### ISSUE TITLE
QUEST: I shoot magic into darkness 

### ISSUE THREAD

**Issue by JosueGarcia08** [NV-WoW/Bugtracker#380]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

https://wowgaming.altervista.org/aowow/?quest=9700

Once you kill 4/5 void anamoly's you no longer get kill count so you can't get 5/5 and finish quest. Probably due to there being a quest follow that you instantly pick up from being in the zone.

### Expected Blizzlike Behaviour

You kill the monster and get kill count to finish the quest

### Steps to reproduce the problem

Kill the anamoly and you wont get credit after 4/5

**Comment by Grindknock** [comment]
Fixed
