### ISSUE TITLE
QUEST: Mac'Aree Mushroom Menagrie

### ISSUE THREAD

**Issue by JosueGarcia08** [NV-WoW/Bugtracker#381]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

https://wowgaming.altervista.org/aowow/?quest=9648

The three following quest item's do not spawn in the world. Rendering you unable to progress and complete quest
Blood Mushroom
Ruinous Polyspore
Fel Cone Fungus

### Expected Blizzlike Behaviour

The items are actually spawned and you can interact with the object to loot them.

### Steps to reproduce the problem

Accept quest and try to go find them

**Comment by Grindknock** [comment]
Fixed
