### ISSUE TITLE
NPC - ID 272 - Chef Grual

### ISSUE THREAD

**Issue by BlazertheAshbringer** [NV-WoW/Bugtracker#383]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

Generic

### Current Behaviour

There is 2 Chef Grual in duskwood darkshire.
https://wowgaming.altervista.org/aowow/?npc=272

https://i.imgur.com/OUXyLOK.png

### Expected Blizzlike Behaviour

https://i.imgur.com/OUXyLOK.png

### Source

https://i.imgur.com/OUXyLOK.png

### Steps to reproduce the problem

https://i.imgur.com/OUXyLOK.png

### Extra Notes

https://i.imgur.com/OUXyLOK.png

**Comment by Grindknock** [comment]
Fixed
