### ISSUE TITLE
[Quest][Azshara] The Pinnacle of Learning (ID24)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#385]
### What client do you play on?

Full (From Other Server)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

1-20

### Current Behaviour

When you accept the quest, nothink happened.

### Expected Blizzlike Behaviour

When you accept the quest, you should be polymorphed to Uleashed Magic and moved to the base of the arcane pinnacle.

https://www.youtube.com/watch?v=eOrU9L9pKSo

### Source

https://www.wowhead.com/quest=14413/the-pinnacle-of-learning
https://www.youtube.com/watch?v=eOrU9L9pKSo

### Steps to reproduce the problem

1. Take the quest

**Comment by Grindknock** [comment]
Fixed
