### ISSUE TITLE
Quest - 14157 - Missing Old Divisions Worgen starting zone as priest

### ISSUE THREAD

**Issue by BlazertheAshbringer** [NV-WoW/Bugtracker#386]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

Generic

### Current Behaviour

After you report quest to priest trainer, King Genn Greyman doesnt give quest Old Division.
King Genn Greymane: https://i.imgur.com/lxyufkv.png
https://www.wowhead.com/quest=14157/old-divisions
https://www.youtube.com/watch?v=LNQK06ezJI0

### Expected Blizzlike Behaviour

After you report quest to priest trainer, Lord Godfrey and King Genn Greyman will give you quest Old Divisions and While You're At It.

### Source

https://www.wowhead.com/quest=14157/old-divisions
https://www.youtube.com/watch?v=LNQK06ezJI0

### Steps to reproduce the problem

https://www.wowhead.com/quest=14157/old-divisions
https://www.youtube.com/watch?v=LNQK06ezJI0

**Comment by Grindknock** [comment]
Fixed
