### ISSUE TITLE
Quest - 24438 - Exodus - Worgen Hunter

### ISSUE THREAD

**Issue by BlazertheAshbringer** [NV-WoW/Bugtracker#387]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

Generic

### Current Behaviour

Carriage below Greymane Manor is missing.
https://i.imgur.com/6wzC2Lu.png
https://www.wowhead.com/quest=24438/exodus

### Expected Blizzlike Behaviour

https://i.imgur.com/QVOOl5c.jpg
https://www.youtube.com/watch?v=x9oL3GK1778

### Steps to reproduce the problem

https://www.youtube.com/watch?v=x9oL3GK1778
https://www.wowhead.com/quest=24438/exodus

**Comment by Grindknock** [comment]
Did you try to relog?

**Comment by BlazertheAshbringer** [comment]
Reloging works. Fixed !!!
