### ISSUE TITLE
quest : 26720 a curse we cannot lift 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#389]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

upon entering the room the worgen spawns inside the wall  out of line of sight 

quest : https://www.wowhead.com/quest=26720/a-curse-we-cannot-lift
npc : https://www.wowhead.com/npc=43799/lurking-worgen

### Expected Blizzlike Behaviour

upon entering the room the worgen spawns in the rafters and jumps down in the room 

### Source

https://www.youtube.com/watch?v=wpFtCQ7b9SU

### Steps to reproduce the problem

1. pick up the quest 
2. enter the room 

### Extra Notes

can currently be done using an aoe to pull the worgen out of the wall

**Comment by Grindknock** [comment]
Fixed
