### ISSUE TITLE
npc : 1550 : thrashtail basilisk multispawns 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#391]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

thrashtail basilisk seems to all be double spawned outside the cave 

npc - https://www.wowhead.com/npc=1550/thrashtail-basilisk#drops
npc - https://www.wowhead.com/npc=44113/ironjaw-behemoth

### Expected Blizzlike Behaviour

each spawn should only have one basilisk

### Source

https://www.youtube.com/watch?v=V10BL3jjJwA

you can see normal spawning through the quest video 

### Steps to reproduce the problem

1. go to the basilisk cave in stranglethorn cape 
2. check spawns

**Comment by Grindknock** [comment]
Fixed
