### ISSUE TITLE
quest : 26814 : High Priest Venoxis ( northern stranglethorn ) 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#393]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

high priest venoxis is in the green bubble from the start event dosnt happend snakes do not spawn  fighting venoxis is rather pointless considering he is a boss with 300 000 hp 

quest - https://www.wowhead.com/quest=26814/high-priest-venoxis
npc - https://www.wowhead.com/npc=52155/high-priest-venoxis

### Expected Blizzlike Behaviour

venoxis should be walking around and start an even after being attacked where snakes try to come up to heal him 

### Source

https://www.youtube.com/watch?v=3vxIR63Trsk

### Steps to reproduce the problem

1. walk up to venoxis 
2. damage him to check if even starts

**Comment by Grindknock** [comment]
fixed
