### ISSUE TITLE
quest - 26597 -  the heart of mokk

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#394]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

when starting the sumoning with witch doctor unbagwa the gorillas just spawn right on top of him and attack him 

- quest : https://www.wowhead.com/quest=26597/stranglethorn-fever
- npc : https://www.wowhead.com/npc=1449/witch-doctor-unbagwa
- item : https://www.wowhead.com/item=2799/gorilla-fang
- unbagwa quest to spawn gorillas : https://www.wowhead.com/quest=26598/the-heart-of-mokk

### Expected Blizzlike Behaviour

the gorillas are suposed to spawn down the hill and run up to the cave 

### Source

https://www.youtube.com/watch?v=CWusRJmbLQ4

### Steps to reproduce the problem

1. gather a gorilla fang 
2. talk to ungawa to start his repeatable quest
3. see how the gorilla spawn

**Comment by Grindknock** [comment]
Fixed
