### ISSUE TITLE
quest - 26697 - the final voyage of the brashtide

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#395]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

upon talking to kebok he dosnt have any dialogue option 

- quest : https://www.wowhead.com/quest=26697/the-final-voyage-of-the-brashtide
- npc : https://www.wowhead.com/npc=737/kebok

### Expected Blizzlike Behaviour

upon talking to kebok there is a dialogue option to summon one of his windrider to start the attack 

### Source

https://www.youtube.com/watch?v=0qIcUqSziNA

### Steps to reproduce the problem

1. pick up the quest 
2. go talk to kebok 

### Extra Notes

there also seem to be no actual phasing in booty bay all the npc's are present at all time

**Comment by Grindknock** [comment]
Fixed
