### ISSUE TITLE
quest : 26633: Swabbing duty ( stv cape )

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#396]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

upon click the broom you dont pick it up and the event dosnt start 

quest : https://www.wowhead.com/quest=26633/swabbing-duty

### Expected Blizzlike Behaviour

picking up a broom will start an event that spaws blobs on the floor that you have to right click to swab 

### Source

https://www.youtube.com/watch?v=i4dJpfiEKLg

### Steps to reproduce the problem

1. get the quest 
2. pick up the broom

**Comment by Grindknock** [comment]
Option 1) Speak with "Pretty Boy" Duncan, using the gossip and the quest has been completed.
Reference: https://www.youtube.com/watch?v=fUcivvTRmoA&t=1s&ab_channel=GitGudGuides

Option 2) Picking up the broom, the event started, and you need to swipe the stains.

FIXED
