### ISSUE TITLE
quest : 26128 : the battle of thandolspan

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#397]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

killing the npc for the quest instantly completes the quest not letting choose your reward and automatically gives you the plate reward ( leather wearing character ) the even suposed to happend on the bridge before the kill is also missing 

quest - https://www.wowhead.com/quest=26128/the-battle-of-thandol-span

### Expected Blizzlike Behaviour

arrive on the bridge with your ally npc  , fight the dwarf group   , the quest should pop up on your screen and let you choose your reward when the event is over 

### Source

https://www.youtube.com/watch?v=sYwSRQdg-Fo

### Steps to reproduce the problem

1. get the quest 
2. go to the bridge and kill the npc

**Comment by Grindknock** [comment]
fixed
