### ISSUE TITLE
npc : 264 / 107837 : commander althea ebonlocke

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#398]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

there is two of her in duskwood one is the normal npc the other one is most likely the assassination artefact quest npc wich is currently located in the mayor's room in duskwood  she is level 98 and hostile 

- the npc that should stay : https://www.wowhead.com/npc=264/commander-althea-ebonlocke#comments
- the npc from the artefact questline that shouldnt be there : https://www.wowhead.com/npc=107837/commander-althea-ebonlocke#objective-of

### Expected Blizzlike Behaviour

only the friendly npc should be present in duskwood unless on the quest for assassination artefact 

### Source

artefact quest version of duskwood:  https://www.youtube.com/watch?v=luT2gIrNqpQ
quest in the room of the mayor 

normal version of the mayor room with no aggressive npc at the start of the video : https://www.youtube.com/watch?v=ErOLhjpgCA8

### Steps to reproduce the problem

1. go to the mayor's room in duskwood 
2. find level 98 hostile npc in the room

**Comment by Grindknock** [comment]
fixed
