### ISSUE TITLE
quest : 26667 : the stolen letters / 26669 in a dark corner ( duskwood ) 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#399]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

when interacting with the stolen letter quest object it gives you the quest items for both quests 
- quest : https://www.wowhead.com/quest=26667/the-stolen-letters
- quest 2  : https://www.wowhead.com/quest=26669/in-a-dark-corner

### Expected Blizzlike Behaviour

only the item a slashed bundle of letters should be looted during the quest the stolen letters 

### Source

https://www.youtube.com/watch?v=McrcZURCTvE&t=57s

### Steps to reproduce the problem

1. get the quest the stolen letters 
2. go and loot the quest objective 
3. check what you get

**Comment by Grindknock** [comment]
Fixed
