### ISSUE TITLE
quest  : 14338 : ghost walker post ( desolace )

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#400]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

quest is available to alliance players 

### Expected Blizzlike Behaviour

quest should only be available to horde players 

### Source

https://www.wowhead.com/quest=14338/ghost-walker-post

### Steps to reproduce the problem

1. use alliance character 
2. grab the quest from Karnum Marshweaver in desolace

**Comment by Grindknock** [comment]
Fixed
