### ISSUE TITLE
reputation kills 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#402]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

Generic

### Current Behaviour

currently every monster that is suposed to give out reputation upon being killed does not 

a few npc 

Timbermaw Hold
- https://wowhead.com/search?q=deadwood#npcs
- https://wowhead.com/search?q=winterfall#npcs

goblind towns rep 
- https://www.wowhead.com/npcs/humanoids/name:Wastewander?filter=6;440;0
- https://www.wowhead.com/npcs/humanoids/name:Southsea?filter=6;440;0

also the city reputation tabards dont seem to have any effects in dungeons 

### Expected Blizzlike Behaviour

---

### Source

links above

### Steps to reproduce the problem

1. find any of the npc listed 
2. kill them with reputation enabled in your chat settings ( proof that you aint gaining any rep ) 
3. check your character reputations to see it unchanged

**Comment by Grindknock** [comment]
Fixed
