### ISSUE TITLE
quest : 14337 : shadowprey village 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#403]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

quest is available to alliance players 

### Expected Blizzlike Behaviour

quest should be horde only 

### Source

https://www.wowhead.com/quest=14337/shadowprey-village

### Steps to reproduce the problem

1. pick up the quest from Karnum marshweaver as an alliance character

**Comment by Grindknock** [comment]
Fixed
