### ISSUE TITLE
quest  : 25368 : Verinias the twisted 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#407]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

the quest items cant be used even right next to the tree it dosnt seem to take it into accounts  
get the message  ' requiere Verinias's Tree "

quest - https://www.wowhead.com/quest=25368/verinias-the-twisted#comments
item   - https://www.wowhead.com/item=54456/mournful-essence
npc    - https://www.wowhead.com/npc=40136/verinias-the-twisted

### Expected Blizzlike Behaviour

using the item next to the tree should spawn the quest npc 

### Source

https://www.youtube.com/watch?v=Bn5n5Xxqdd0

### Steps to reproduce the problem

1. pick up the quest 
2. go next to the tree 
3. try to use quest item

**Comment by Grindknock** [comment]
fixed
