### ISSUE TITLE
Npc : 2502 : "Shaky" Philipe

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#409]
### What client do you play on?

Full (Clean Download)

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

npc is double spawned in booty bay down by the ramp 

### Expected Blizzlike Behaviour

there should be only one 

### Source

https://www.wowhead.com/npc=2502/shaky-phillipe

### Steps to reproduce the problem

1. go to booty bay 
2. remove one of them

**Comment by Grindknock** [comment]
fixed
