### ISSUE TITLE
quest : 26041 : stones of binding 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#410]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

upon looting the cresting key at the stone of east binding you also get the webwood egg wich is a quest item for a level 5 quest in shadowglen 

quest - https://www.wowhead.com/quest=26041/stones-of-binding
item   - https://www.wowhead.com/item=4484/cresting-key
wrong item  - https://www.wowhead.com/item=5167/webwood-egg ( item was removed in bfa as the region was deleted ) 

### Expected Blizzlike Behaviour

you should only get the cresting key 

### Source

https://www.wowhead.com/quest=26041/stones-of-binding

### Steps to reproduce the problem

1. grab the quest 
2. go loot the cresting key

**Comment by Grindknock** [comment]
fixed
