### ISSUE TITLE
npcs : 108824 / 108815 / 108847  level 98 in western plaguelands

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#412]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

all those npc are present in the normal questing area 

- https://www.wowhead.com/npc=108815/anguished-spectre#objective-of
- https://www.wowhead.com/npc=108847/disturbed-resident
- https://www.wowhead.com/npc=108824/disturbed-resident

### Expected Blizzlike Behaviour

those npc should only be there during the paladin class hall campain quest 

https://www.wowhead.com/quest=42771/keeping-the-peace

### Source

https://www.youtube.com/watch?v=lJg2d0Btt_4
( normal leveling quest where you can see that there is no agressive level 98 npc attacking 

### Steps to reproduce the problem

1. go to the zone 
2. check the npc around

**Comment by Grindknock** [comment]
fixed
