### ISSUE TITLE
herbalism

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#413]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

Generic

### Current Behaviour

at about level 20 / 30 herbalism all plants turn grey  making it very hard to level  some plants later on need you to have 225 herbalism 

### Expected Blizzlike Behaviour

plants should have different levels making you able to actually level your profession 

### Source

https://wowpedia.fandom.com/wiki/Herb

that page has a table of all herb levels 

### Steps to reproduce the problem

1. pick up herbalism 
2. gather plants till you reach herbalism 30  ( might be less than 30 )

**Comment by Grindknock** [comment]
fixed
