### ISSUE TITLE
Missing Weapon

### ISSUE THREAD

**Issue by ItamedMisha** [NV-WoW/Bugtracker#414]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

Generic

### Current Behaviour

Logged out after completing https://www.wowhead.com/quest=26322/rise-of-the-brotherhood and selecting https://www.wowhead.com/item=58931/house-wrynn-claymore?bonus=6691 as my reward. Upon logging back in I had no weapon equipped. Thankfully I hadn't sold my previous weapon but it's still really sad seeing as it does half the damage and has less than half the stats.

### Expected Blizzlike Behaviour

Not to loose the sword.

### Steps to reproduce the problem

Select House Wrynn Claymore as reward, log out and log back in.

**Comment by Grindknock** [comment]
Fixed
