### ISSUE TITLE
Missing Hearthstone

### ISSUE THREAD

**Issue by ItamedMisha** [NV-WoW/Bugtracker#415]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

Generic

### Current Behaviour

Logged out and the next day log in to see I have no hearthstone.

### Expected Blizzlike Behaviour

To not have my HS be deleted.

### Steps to reproduce the problem

Log out with a HS log back in

**Comment by Grindknock** [comment]
Fixed
