### ISSUE TITLE
quest : 26473 : bathran's hair ( ashenvale )

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#417]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

currently  bathran's hair nodes are not clickable / enabled so character is unabled to pick them up 

quest - https://www.wowhead.com/quest=26473/bathrans-hair
object - https://www.wowhead.com/item=5437/bathrans-hair

### Expected Blizzlike Behaviour

bathran's hair should be clickable when on the quest 

### Source

https://www.youtube.com/watch?v=fTORjiCQV7s&t=4s

### Steps to reproduce the problem

1. pick up the quest 
2. try to pick up the item

**Comment by Grindknock** [comment]
fixed
