### ISSUE TITLE
quest : 13924 : all's well 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#418]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

cant deliver the item to the npc 

quest  - https://www.wowhead.com/quest=13924/alls-well
npc - https://www.wowhead.com/npc=3894/pelturas-whitemoon
object - https://www.wowhead.com/item=46715/sanctified-moonstones

### Expected Blizzlike Behaviour

the npc is suposed to accept the item to finish the quest 

### Source

https://www.youtube.com/watch?v=8mciWIDawTo&t=22s

### Steps to reproduce the problem

1. pick up the quest 
2. deliver it

**Comment by Grindknock** [comment]
Fixed
