### ISSUE TITLE
quest : 26474 : orendil's cure 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#419]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

cannot deliver the quest item to the npc 

- quest : https://www.wowhead.com/quest=26474/orendils-cure
- npc : https://www.wowhead.com/npc=3894/pelturas-whitemoon
- quest item : https://www.wowhead.com/item=5460/orendils-cure

### Expected Blizzlike Behaviour

the npc should accept the quest item to finish the quest 

### Source

https://www.youtube.com/watch?v=PJFsnkszYmo

### Steps to reproduce the problem

1. pick up the quest 
2. deliver the quest

**Comment by Grindknock** [comment]
Fixed
