### ISSUE TITLE
quest : 26467 : vile satyr dryads in danger

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#421]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

the npc to deliver the quest seems to be missing 

### Expected Blizzlike Behaviour

the npc should be waiting for you to deliver the quest 

### Source

https://www.youtube.com/watch?v=RXPjdvfC_Hg

### Steps to reproduce the problem

1. pick up the quest 
2. try to find the npc to deliver it

**Comment by Grindknock** [comment]
fixed
