### ISSUE TITLE
quest  : 13886 :  Vortex

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#422]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

the quest boss is constantly reseting  going back to full health 

- quest : https://www.wowhead.com/quest=13886/vortex
- npc : https://www.wowhead.com/npc=34333/lord-magmathar-kill-credit-bunny

### Expected Blizzlike Behaviour

the npc should not reset 

### Source

https://www.youtube.com/watch?v=aHkbHY19AuI

### Steps to reproduce the problem

1. pick up the quest 
2. jump in the elemental 
3. try to kill the boss

**Comment by Grindknock** [comment]
fixed
