### ISSUE TITLE
quest : 13935 : Defend the tree 

### ISSUE THREAD

**Issue by KingOopsed** [NV-WoW/Bugtracker#423]
### What client do you play on?

Full (Clean Download)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

20-40

### Current Behaviour

the quest npc is missing the dialogue to start the defense event 

### Expected Blizzlike Behaviour

npc should offer a dialogue option to start the event 

### Source

https://www.youtube.com/watch?v=y1wNusNnthU

### Steps to reproduce the problem

1. pick up the quest 
2. talk to the npc  you got the quest from

**Comment by Grindknock** [comment]
fixed
