### ISSUE TITLE
[Quest] Rewards missing

### ISSUE THREAD

**Issue by MrDeadNoob** [NV-WoW/Bugtracker#424]
### What client do you play on?

Minimal

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Quest dont give reward for Mail Classes(Hunter & Shaman)

![WoWScrnShot_092321_102046](https://user-images.githubusercontent.com/67128126/134475711-7c8cbf86-3da3-4507-88e6-b39e1475dd72.jpg)

### Expected Blizzlike Behaviour

https://www.wowhead.com/quest=10303/the-blood-elves

Reward with gear are with mail for Hunters or Shamans

### Source

N.A.

### Steps to reproduce the problem

Just take the Quest

**Comment by Grindknock** [comment]
Fixed
