### ISSUE TITLE
[Quest][ID: 9528] A Cry For Help

### ISSUE THREAD

**Issue by MrDeadNoob** [NV-WoW/Bugtracker#425]
### What client do you play on?

Minimal

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

NPC is following until destinatiob is reached but quest is not completed

### Expected Blizzlike Behaviour

Should like this => https://www.youtube.com/watch?v=dZ5Kb-dsXrQ

https://www.wowhead.com/quest=9528/a-cry-for-help

### Source

N.A.

### Steps to reproduce the problem

Accept Quest und follow the NPC

### Extra Notes

WoWHead: https://www.wowhead.com/quest=9528/a-cry-for-help

**Comment by Grindknock** [comment]
Fixed
