### ISSUE TITLE
[NPC][ID: 17554] Laando <Hippogryph Master>

### ISSUE THREAD

**Issue by MrDeadNoob** [NV-WoW/Bugtracker#426]
### What client do you play on?

Minimal

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

NPC has option to fly to other places

### Expected Blizzlike Behaviour

NPC should have the same window as every other Hippogryph Master

### Steps to reproduce the problem

Speak to him and try to fly to Exodar for example

### Extra Notes

https://www.wowhead.com/npc=17554/laando

NPC Flag '8192' is missing (https://trinitycore.atlassian.net/wiki/spaces/tc/pages/1203568708/creature+template+master#creature_template(master)-npcflag)

**Comment by Grindknock** [comment]
Fixed
