### ISSUE TITLE
[Quest][Darkshore] The Last Wave of Survivors (Q=13518)

### ISSUE THREAD

**Issue by TigerFist1983** [NV-WoW/Bugtracker#46]
Objectives not exists
[https://www.wowhead.com/quest=13518/the-last-wave-of-survivors](url)
![WoWScrnShot_080321_085414](https://user-images.githubusercontent.com/86138081/127958000-2481160d-2e63-4be0-8d55-aa32a9dcdf10.jpg)

**Comment by wr4i7h-gg** [comment]
Fixed
