### ISSUE TITLE
[NPC] Golnir Bouldertoe 4256

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#48]
NPC [Golnir Bouldertoe](https://www.wowhead.com/npc=4256/golnir-bouldertoe) is supposed to be selling mining supplies but the selling window can't be activated, instead there is just a window with a text. Might or might not be associated with Ride to Ironforge quest, cause this quest ends with this NPC.
![WoWScrnShot_080321_072923](https://user-images.githubusercontent.com/88363212/127962772-d9cbf1f5-edf7-4841-8623-487f3beccad3.jpg)

**Comment by wr4i7h-gg** [comment]
Fixed
