### ISSUE TITLE
[Quest] Human Starting Zone Quests

### ISSUE THREAD

**Issue by PhoenixTV1337** [NV-WoW/Bugtracker#5]
Describe the bug:
The Quest ''Vineyard fire extinguished'' fires sometimes dont actually get put out also with that the orcs take damage from the fire when they actually shouldnt and they also dont reset their hp to full.

To Reproduce:
Use Milly's Fire Extinguisher towards a fire sometimes doesnt put it out.

Desktop (please complete the following information):

OS: [Windows]
Client [Full Client]
Additional context: You can also not just turn your characther while using the extinguisher to put out other fires nearby

**Comment by PhoenixTV1337** [comment]
Some other context the orcs tend to have a quiet really large aggro radius

**Comment by Grindknock** [comment]
Fixed
