### ISSUE TITLE
[Quest] A Decisive Strike

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#50]
After completing prequests https://www.wowhead.com/quest=26145/the-trogg-threat and https://www.wowhead.com/quest=26147/bigger-and-uglier the NPC https://www.wowhead.com/npc=1092/captain-rugelfuss doesn't give following quest a Decisive Strike https://www.wowhead.com/quest=26148/a-decisive-strike

**Comment by jacobx97** [comment]
I have just completed "The Trogg Threat" and "Bigger and Uglier" and I got "A Decisive Strike" quest.

**Comment by Trazzyx** [comment]
After further checking i saw that i didn't do one more prequest originating from Dun Morogh, thanks for info about completion. Consider it solved
