### ISSUE TITLE
[Item spawn] World double spawns (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#52]
What client do you play on?
Full clean install
Faction
 Alliance
Content Phase:
1-20
Current Behaviour
There are some double ores spawned in loch modan:
Ores:
Loch modan, 71.60 49.95 
Loch modan, 78.70, 46.89
Loch modan, 68.66, 32.37
Expected Blizzlike Behaviour
There should be no double spawns
Source
TP to location and see for yourself.

**Comment by xadowtek** [comment]
-- Fix Solaped Veins on Loch Modan
UPDATE gameobject SET position_x = '-5409.76' WHERE guid = 63479;
UPDATE gameobject SET position_x = '-5407.76' WHERE guid = 63554;
UPDATE gameobject SET position_x = '-5306.44' WHERE guid = 63629;
UPDATE gameobject SET position_x = '-5302.71' WHERE guid = 63478;
UPDATE gameobject SET position_x = '-5348.16' WHERE guid = 63480;
UPDATE gameobject SET position_x = '-5350.16' WHERE guid = 63535;
DELETE FROM gameobject WHERE guid = 63537;
