### ISSUE TITLE
Crystal vials cannot be bought

### ISSUE THREAD

**Issue by Narutohell** [NV-WoW/Bugtracker#54]
Describe the bug:
it seems can't afford crystal vials from vendor while i have the money required.

To Reproduce:

Go to: '....'
Go to General goods vendor.
Action: (Quest.-/Object.-/Creature.-/Spell.-/Other related) '....'
Try buying Crystal vial for alchemy
Current behaviour: '....'
u can't afford the money to buy it.
Expected behaviour: '....'
u can afford the money to buy it.
Wowhead link: 'https://wowhead.com/....'
Server revision: 'Closed Alpha/Closed Beta/Beta vX....'
Game event areas, quests, vendors, etc should be present during the seasonal event period, and must be mentioned as [EVENT_NAME] tag.

**Comment by Grindknock** [comment]
Fixed
