### ISSUE TITLE
[Quest] A Favor for Melithar (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#55]
What client do you play on?
Full clean install
Faction
 Alliance
Content Phase:
1-20
Current Behaviour
After completing quest https://www.wowhead.com/quest=28714/fel-moss-corruption there should be follow up quest https://www.wowhead.com/quest=28734/a-favor-for-melithar but no quest is offered.
Expected Blizzlike Behaviour
favor for melithar quest should be open for me to take.
Source
https://www.wowhead.com/quest=28734/a-favor-for-melithar
Steps to reproduce the problem
1. complete fel moss corruption
2. that's it.

**Comment by Grindknock** [comment]
Fixed
