### ISSUE TITLE
[Quest][Loch Modan] Filthy Paws - Miner's League Crates (not critical)

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#60]
If you click on the crates, do not take the item and close loot dialog, crates disepeared. I think it should not happend until you take the item from it. Or am I wrong?

Wowhead links: 
https://www.wowhead.com/quest=307/filthy-paws
https://www.wowhead.com/object=271/miners-league-crates

**Comment by wr4i7h-gg** [comment]
Fixed
