### ISSUE TITLE
[Quest] The Stolen Letters

### ISSUE THREAD

**Issue by l0ssm1** [NV-WoW/Bugtracker#61]
A slashed Bundle of Letters that is used for quest is obtainable only through "Pile of Scrap" but that pile of scrap doesn't give anything. When opened it shows nothing inside. It might have bugged just for me, I didn't have time to test it again.

Wowhead link [QUEST]: https://www.wowhead.com/quest=26667/the-stolen-letters
Wowhead link [QUEST ITEM CONTAINER]: https://www.wowhead.com/object=204462/pile-of-scraps
Wowhead link [QUEST ITEM]: https://www.wowhead.com/item=59357/a-slashed-bundle-of-letters

**Comment by wr4i7h-gg** [comment]
fixed
