### ISSUE TITLE
Elixir stacking the effect

### ISSUE THREAD

**Issue by Narutohell** [NV-WoW/Bugtracker#64]
Describe the bug:
i crafted a potion that have effect on u(lasts 2h) and it seems stackable .

To Reproduce:

Go to: '....'
Drink an elixir that have an effect on u 
Action: (Quest.-/Object.-/Creature.-/Spell.-/Other related) '....'
It seems all the pots do the same
Current behaviour: '....'
it stacks the effect and number of flasks
Expected behaviour: '....'
when u drink it 2nd time it should refresh only the duration for elixir u already drank
Wowhead link: 'https://wowhead.com/....'
Server revision: 'Closed Alpha/Closed Beta/Beta vX....'
Game event areas, quests, vendors, etc should be present during the seasonal event period, and must be mentioned as [EVENT_NAME] tag.

**Comment by wr4i7h-gg** [comment]
Elixir's name?

**Comment by Narutohell** [comment]
it's fixed i don't get anymore stacks (it was all elixirs)
