### ISSUE TITLE
[Spell] Titan's grip bugged

### ISSUE THREAD

**Issue by Narutohell** [NV-WoW/Bugtracker#65]
Describe the bug:
It seems i can't equip 2handed weapon in my offhand while in Fury Spec

To Reproduce:

Go to: '....'
Try equiping a 2 handed weapon on ur offhand
Action: (Quest.-/Object.-/Creature.-/Spell.-/Other related) '....'
Spell named Titan's grip
Current behaviour: '....'
I can't equip 2handed weapon on my off hand
Expected behaviour: '....'
i can equip a 2 handed weapon in each hand
Wowhead link: 'https://www.wowhead.com/spell=46917/titans-grip'
Server revision: 'Closed Alpha/Closed Beta/Beta vX....'
Game event areas, quests, vendors, etc should be present during the seasonal event period, and must be mentioned as [EVENT_NAME] tag.

**Comment by wr4i7h-gg** [comment]
INVALID Report

With Titan's Grip active:
![image](https://user-images.githubusercontent.com/75091460/128136377-c97dea4e-435a-42b6-a80f-a9a1a5302b84.png)
![image](https://user-images.githubusercontent.com/75091460/128136573-f899aa40-b829-4cb7-be70-e70eb5a00585.png)

Without Titan's Grip:
![image](https://user-images.githubusercontent.com/75091460/128136459-ceb7b72c-2998-40f2-9887-c82dde614456.png)
