### ISSUE TITLE
[Model/Quest] Fire Extinguisher stays on my character after the quest Extinguishing Hope

### ISSUE THREAD

**Issue by Thovia** [NV-WoW/Bugtracker#68]
/reload did not fix the issue

![image](https://user-images.githubusercontent.com/64737510/128010255-b7c9f6f5-37d0-4718-8f7d-b5b27b0adacc.png)

**Comment by Thovia** [comment]
Update: Logging out to character selection screen and back in fixes the issue

**Comment by Grindknock** [comment]
Fixed
