### ISSUE TITLE
[Quest] Murder Was The Case That They Gave Me

### ISSUE THREAD

**Issue by JadedNate** [NV-WoW/Bugtracker#78]
The player should be able to speak with West Plain Drifters [ID:42391] to obtain the 4 clues for the quest. The NPCs seem to only give the player clue #3 and the speech option "DId you see who killed the Furlbrows?" only causes them to attack the player.

**Comment by JadedNate** [comment]
After the ~25 min since I opened this issue, I was finally able to get all 4 clues. I dropped the quest a few times and just had to wait for all of the Drifters to respawn. Should definitely be looked into :P

**Comment by Trazzyx** [comment]
Temporary workaround:
I think the way it works on other realms is - take the quest, go to place, abandon quest. While they are talking take quest again and aggro them, that way you should get all the clues.

**Comment by Grindknock** [comment]
fixed
