### ISSUE TITLE
Pets on Defensive do not attack.

### ISSUE THREAD

**Issue by JamesGent** [NV-WoW/Bugtracker#8]
**Describe the bug:**
Pets on Defensive do not attack. If my hunter shoots a target, the pet does nothing. If I am attacked by a target, my pet does nothing.

**To Reproduce:**
1. Go to: '....'

Create lvl 1 hunter.

2. Action: (Quest.-/Object.-/Creature.-/Spell.-/Other related) '....'

Put pet to defensive and attack a target.

3. Current behaviour: '....'

Pet refuses to engage.

4. Expected behaviour:  '....'

Pet should engage.

5. Wowhead link: 'https://wowhead.com/....'
6. Server revision: 'Closed Alpha/Closed Beta/Beta vX....'

Game event areas, quests, vendors, etc should be present during the seasonal event period, and must be mentioned as [EVENT_NAME] tag.

**(Not necessary but recommended) Screenshots:**

**(Not necessary but recommended) Videos:** 
If applicable, add a streamable (as an example) video link to help explain your problem.
(Recommended to use streamable website for example)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64 bit]
 - Client [e.g. Minimal Client or Full Client]

**Additional context**:

**Comment by wr4i7h-gg** [comment]
After level 10, the pet is defending the player while the Defensive stance is active.
Below level 10, the pet is not a fully functional one.

**Comment by wr4i7h-gg** [comment]
Closed, and placed into the pinned post.
https://github.com/NV-WoW/Bugtracker/issues/14
