### ISSUE TITLE
[Quest] The last wildkin (ID41)

### ISSUE THREAD

**Issue by Trazzyx** [NV-WoW/Bugtracker#83]
What client do you play on?
Full clean install
Faction
 Alliance
Content Phase:
1-20
Current Behaviour
Aroom is not there, so the quest can't be completed.
Expected Blizzlike Behaviour
Aroom should be there after taking the quest.
Source
https://www.wowhead.com/quest=13577/the-last-wildkin
Steps to reproduce the problem
1. take quest 
2. go to marked location

**Comment by AlainBx20** [comment]
issue closed.
NPC confirmed to be in place and quest completable.
![image](https://user-images.githubusercontent.com/88325996/128082251-eadd1187-7074-4c0f-bcad-47badd5ac702.png)
![image](https://user-images.githubusercontent.com/88325996/128082233-09c457b4-e73f-4648-bc4b-f5bf4cbf33fe.png)

**Comment by Trazzyx** [comment]
Further comments: I think this quest share the same issue as [79](https://github.com/NV-WoW/Bugtracker/issues/79) , [80](https://github.com/NV-WoW/Bugtracker/issues/80) and [82](https://github.com/NV-WoW/Bugtracker/issues/82)

Issue was closed because Aroom was there for AlainBx20, but I still can't see it. This might be a phase issue rather than NPC spawn issue.
