### ISSUE TITLE
Ragefire Chasm [Alliance]

### ISSUE THREAD

**Issue by JadedNate** [NV-WoW/Bugtracker#84]
Alliance NPCs are missing from Ragefire Chasm, with the following quests:
https://www.wowhead.com/quest=30998/a-new-enemy
https://www.wowhead.com/quest=30995/no-man-left-behind
https://www.wowhead.com/quest=30996/the-dark-shaman

**Comment by JadedNate** [comment]
Missing NPCs:
https://www.wowhead.com/npc=61823/high-sorceress-aryna
https://www.wowhead.com/npc=61822/si-7-field-commander-dirken
https://www.wowhead.com/npc=61821/si-7-commando
https://www.wowhead.com/npc=61788/si-7-ranger

**Comment by Grindknock** [comment]
fixed
